services:
  fastapi:
    image: khalandar/fastapi:dev
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8500:8500

  streamlit:
    image: khalandar/streamlit:dev
    build:
      context: .
      dockerfile: dockerfile_streamlit
    ports:
      - 8501:8501
    environment:
      - API_URL=http://fastapi:8500
